@url=http://localhost:5557

### GET JOBS
GET {{url}}/jobs

### GET JOB
GET {{url}}/jobs/ca63

### POST JOB

POST {{url}}/jobs
content-type:application/json

{
    "jobTitle":"PHP Developer",
    "description": "Requires vue.js "
}

### DELETE JOB
DELETE {{url}}/jobs/7f66